name: MOTOPP CI/CD

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: motopp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # -------- Stage 1: Build & Install --------
      - name: Install deps
        working-directory: motopp
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install flake8 bandit pytest

      # -------- Stage 2: Lint/Security --------
      - name: Lint (flake8)
        run: flake8 motopp --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Security scan (bandit)
        run: bandit -r motopp -x motopp/tests || true

      # -------- Stage 3: Test (with DB) --------
      - name: Wait for DB
        run: |
          for i in {1..60}; do
            mysqladmin ping -h 127.0.0.1 -uroot && break
            sleep 1
          done

      - name: Run tests
        env:
          # match your running compose: root with empty password
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_DATABASE: motopp
          SECRET_KEY: dummy
        run: |
          # if no tests exist, this won't fail the pipeline
          pytest || echo "No tests / optional tests skipped."

      # -------- Stage 4: Build Docker Image --------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t motopp-app:ci motopp

      # -------- Stage 5: Deploy  --------
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      #------- Stage 6: Push to Docker Hub --------
      - name: Tag & Push image to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Pushing as ${{ secrets.DOCKER_USERNAME }}/motopp:latest"
          docker tag motopp-app:ci ${{ secrets.DOCKER_USERNAME }}/motopp:latest
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/motopp:latest